
get-igrf-coefficients:
	wget http://www.ngdc.noaa.gov/IAGA/vmod/igrf11coeffs.txt
	wget http://www.ngdc.noaa.gov/IAGA/vmod/igrf11coeffs.xls
	wget http://www.ngdc.noaa.gov/IAGA/vmod/geomag70_linux.tar.gz

get-yale-bright-star-catalog:
	wget http://tdc-www.harvard.edu/catalogs/BSC5
	wget http://tdc-www.harvard.edu/catalogs/bsc5.dat.gz 
	wget http://tdc-www.harvard.edu/catalogs/bsc5.dat.gz
	wget http://tdc-www.harvard.edu/catalogs/bsc5.notes.gz

get-leap-second-list:
	wget http://maia.usno.navy.mil/ser7/tai-utc.dat
